server:
  port: 8080

spring:
  datasource:
    sql-script-encoding: UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/optimisticlock?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000


# mybatis 的配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  - classpath:mybatis/mapper/*/*.xml
  - classpath*:mybatis/mapper/*/*/*.xml
  type-aliases-package: top.lrshuai.optimisticlock.*.entity

#logging:
#  level:
#    top.lrshuai.optimisticlock.usr.mapper: info

